controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: annotation

front_app:
  resource: '../src/Controller/Front'
  type: annotation
#  schemes:    [https]

admin_app:
  resource: '../src/Controller/Admin'
  type: annotation
  prefix: administration
#  schemes:    [https]